//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaGaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logi
    {
        public int IdLog { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string TextLog { get; set; }
        public Nullable<int> IdPracownika { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
    }
}
