//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaGaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochod()
        {
            this.Zlecenies = new HashSet<Zlecenie>();
        }
    
        public int IdSamochodu { get; set; }
        public Nullable<int> IdKlient { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string NumerRejestracyjny { get; set; }
        public string NumerVIN { get; set; }
        public Nullable<int> DataProdukcji { get; set; }
        public Nullable<int> MocKW { get; set; }
        public Nullable<int> MocKM { get; set; }
        public string Opis { get; set; }
    
        public virtual Klient Klient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zlecenie> Zlecenies { get; set; }
    }
}
