//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaGaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usluga
    {
        public int IdUslugi { get; set; }
        public Nullable<int> IdZlecenia { get; set; }
        public string Nazwa { get; set; }
        public Nullable<double> Cena { get; set; }
        public Nullable<int> IdKategorii { get; set; }
    
        public virtual Zlecenie Zlecenie { get; set; }
        public virtual Kategoria Kategoria { get; set; }
    }
}
