//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaGaApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Id Zlecenia</string>
  <string>Imie klienta</string>
  <string>Nazwisko klienta</string>
  <string>Marka samochodu</string>
  <string>Model auta</string>
  <string>Data przyjęcia zlecenia</string>
  <string>Numer rejestracyjny</string>
  <string>Numer VIN</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Col1ToDo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Col1ToDo"]));
            }
            set {
                this["Col1ToDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection Col2ToDo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Col2ToDo"]));
            }
            set {
                this["Col2ToDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Id Zlecenia</string>
  <string>Imie klienta</string>
  <string>Nazwisko klienta</string>
  <string>Marka samochodu</string>
  <string>Model auta</string>
  <string>Data przyjęcia zlecenia</string>
  <string>Numer rejestracyjny</string>
  <string>Numer VIN</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Col1Done {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Col1Done"]));
            }
            set {
                this["Col1Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection Col2Done {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Col2Done"]));
            }
            set {
                this["Col2Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Id Klienta</string>
  <string>Imie</string>
  <string>Nazwisko</string>
  <string>Numer telefonu</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Col1Klient {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Col1Klient"]));
            }
            set {
                this["Col1Klient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection Col2Klient {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Col2Klient"]));
            }
            set {
                this["Col2Klient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Id Zlecenia</string>
  <string>Imie klienta</string>
  <string>Nazwisko klienta</string>
  <string>Marka samochodu</string>
  <string>Model auta</string>
  <string>Data przyjęcia zlecenia</string>
  <string>Numer rejestracyjny</string>
  <string>Numer VIN</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColZlecenia {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColZlecenia"]));
            }
            set {
                this["ColZlecenia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Id Klienta</string>
  <string>Imie</string>
  <string>Nazwisko</string>
  <string>Numer telefonu</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColKlienci {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColKlienci"]));
            }
            set {
                this["ColKlienci"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSearchDone {
            get {
                return ((string)(this["LastSearchDone"]));
            }
            set {
                this["LastSearchDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSerachToDo {
            get {
                return ((string)(this["LastSerachToDo"]));
            }
            set {
                this["LastSerachToDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSerachKlient {
            get {
                return ((string)(this["LastSerachKlient"]));
            }
            set {
                this["LastSerachKlient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastTimeDone {
            get {
                return ((string)(this["LastTimeDone"]));
            }
            set {
                this["LastTimeDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastTimeToDo {
            get {
                return ((string)(this["LastTimeToDo"]));
            }
            set {
                this["LastTimeToDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastDowolnaDone {
            get {
                return ((global::System.DateTime)(this["LastDowolnaDone"]));
            }
            set {
                this["LastDowolnaDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastDowolnaToDo {
            get {
                return ((global::System.DateTime)(this["LastDowolnaToDo"]));
            }
            set {
                this["LastDowolnaToDo"] = value;
            }
        }
    }
}
